"""empty message

Revision ID: 3c51c9e2318a
Revises: 0b2beec49098
Create Date: 2021-12-06 20:09:52.517614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c51c9e2318a'
down_revision = '0b2beec49098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=True),
    sa.Column('registration_id', sa.String(length=10), nullable=True),
    sa.Column('model_number', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_number'),
    sa.UniqueConstraint('registration_id')
    )
    op.create_index(op.f('ix_product_external_id'), 'product', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_external_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
