"""empty message

Revision ID: 5ec4bf51b7d0
Revises: 3c51c9e2318a
Create Date: 2021-12-06 22:50:36.811178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec4bf51b7d0'
down_revision = '3c51c9e2318a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stand', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stand', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stand', type_='foreignkey')
    op.drop_column('stand', 'user_id')
    # ### end Alembic commands ###
